import type { Metadata } from "next";
import { VT323 } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import ClientImageLoader from "./components/client-image-loader";

const vt323 = VT323({
  variable: "--font-vt323",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const sentex = localFont({
  src: "../../public/fonts/Sentex-Regular.ttf",
  variable: "--font-sentex",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${vt323.variable} ${sentex.variable} antialiased`}>
        <ClientImageLoader>{children}</ClientImageLoader>
      </body>
    </html>
  );
}
